CoMDynamics:
  CoM_translational_gains:
    kp: [ 100, 100, 100 ]
    kd: [ 1, 1, 1 ]
  body_angular_acceleration_gains:
    kp: [ 10, 10, 10 ]
    kd: [ 0.1, 0.1, 0.1 ]
  qp_weight_gain: 1000
  hess_regul: 0.001

ContactWrench:
  k_f: 1.0
  k_mu: 1.0